language: node_js
node_js:
    - "10.10.0"

branches:
    only:
        - master

before_script:
    - npm install -g @angular/material
    - npm install -g @angular/cli

script:
    - ng build --prod

deploy:
    provider: firebase
    token:
        secure: "1/obn4nXvw6rHhrPKWq5Lda0r8BGXegXtk4vDYQTPt2UA"
    project: "szbd-angular"
